<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>

    <!-- NuGet Package Metadata -->
    <PackageId>Mjolnir.Extensions.Exceptions</PackageId>
    <Authors>ThorLL</Authors>
    <Description>Simple MCP server compatible exceptions, http request validators and global handlers</Description>
    <PackageTags>Exception;MCP;HTTP;</PackageTags>
    <PackageProjectUrl>Mjolnir.Extensions.Exceptions</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ThorLL/Mjolnir</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <!-- Build Settings -->
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5"/>
    <PackageReference Include="ModelContextProtocol.Core" Version="1.1.0"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>
